version: '3.8'
services:
  cra:
    build:
      context: ./cra
      target: dev
    volumes:
      - ./cra:/src
    ports:
      - "${REACT_PORT:-5000}:3000"
    environment:
      REACT_APP_APP_NAME: ${APP_NAME}
    networks:
      - exercise-app-network

  # next:
  #   build:
  #     context: ./next
  #     target: dev
  #   volumes:
  #     - ./next:/src
  #   ports:
  #     - "${NEXT_PORT:-3000}:3000"
  #   environment:
  #     REACT_APP_APP_NAME: ${APP_NAME}
  #   networks:
  #     - exercise-app-network
      
  express:
    build:
      context: ./express
      target: dev
    volumes:
      - ./express:/src
    ports:
      - "${NODE_PORT:-8000}:8000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      NODE_PORT: ${NODE_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: mongo
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    networks:
      - exercise-app-network
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4.1.8-xenial
    ports:
      - "${MONGO_PORT:-27018}:27017"
    networks:
      - exercise-app-network
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

networks:
  exercise-app-network:
    external: true
    driver: bridge